name: Presubmit
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited, auto_merge_enabled]
    branches: [main, release]
    
jobs:
  check-version:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout main branch from GitHub 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
        
      - name: Provide script permissions
        run: chmod -R +x ./src/resources/tools
      
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Check version
        run: |
          ./src/resources/tools/version.sh --main-branch ${{ github.base_ref }} --mode validate
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
